name: dynamicalsystem
services:
  gazette:
    image: dynamicalsystem/gazette:latest
    container_name: gazette
    build:
      args:
        - HOST_FOLDER=${HOST_FOLDER}
        - SUBFOLDER=${SUBFOLDER}
    environment:
      - TZ=Europe/London
      - DYNAMICALSYSTEM_ENVIRONMENT=${ENV}
      - DYNAMICALSYSTEM_FOLDER=/
      - HOST_FOLDER=${HOST_FOLDER}
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - kalmanfilter
    volumes:
      - "${HOST_FOLDER}/${SUBFOLDER}:/${SUBFOLDER}"
      #map secrets folder on host system into docker container.
    depends_on:
      - signal
    profiles:
      - scheduled

  signal:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal
    build:
      args:
        - HOST_FOLDER=${HOST_FOLDER}
        - SUBFOLDER=${SUBFOLDER}
    restart: always
    environment:
      - PORT=8010
      - MODE=json-rpc #supported modes: json-rpc, native, normal
      - LOG_LEVEL=debug
      - SIGNAL_CLI_UID=1003
      - SIGNAL_CLI_GID=1003
      # Don't set SIGNAL_CLI_UID/GID for rootless docker
    ports:
      - "${SIGNAL_PORT}:8010" #map docker port 8010 to external port ${SIGNAL_PORT}.
    networks:
      - kalmanfilter
    volumes:
      - type: bind
        source: ${HOST_FOLDER}/${SUBFOLDER}/signal-cli
        target: /home/.local/share/signal-cli
        bind:
          create_host_path: false

networks:
  kalmanfilter:
    driver: bridge
