#!/usr/bin/env bash
# Rebuild the gitignored .env from macOS Keychain-held secrets.
#
# Non-secret values live inline below. Secrets live in the login Keychain
# under service "dynamicalsystem.gazette", account = env var name.
# To (re)store one:
#   security add-generic-password -U -s dynamicalsystem.gazette -a GITHUB_TOKEN -w '<value>'
set -euo pipefail

cd "$(dirname "$0")/.."

kc() { security find-generic-password -s dynamicalsystem.gazette -a "$1" -w; }

umask 077
cat > .env <<EOF
# gazette local DEV config (gitignored). Generated by scripts/build-env.sh --
# edit that script (or the Keychain items), not this file.
# Dev-default: WATERMARK_FILE points at the Validator-only dev set, so running
# \`uv run gazette\` here CANNOT send real messages. Prod is driven by the
# launchd runner, which exports its own flat vars (they override this file).

ENVIRONMENT=dev
LOG_LEVEL=INFO

# content (GitHub raw JSON) -- read-only fine-grained PAT (Contents:Read on
# DynamicalSystem/content); mirrors gazette.prod.env. Verified working 2026-07-07.
GITHUB_URL=https://raw.githubusercontent.com/DynamicalSystem/content/main/
GITHUB_TOKEN=$(kc GITHUB_TOKEN)

# bluesky
BLUESKY_URL=https://bsky.social
BLUESKY_USERNAME=simon@horrobin.net
BLUESKY_PASSWORD=$(kc BLUESKY_PASSWORD)

# signal (local podman container; localhost survives roaming)
SIGNAL_URL=http://localhost:8010
SIGNAL_IDENTITY=$(kc SIGNAL_IDENTITY)

# state -- dev watermarks are Validator-only (dry run)
DATA_FOLDER=${XDG_DATA_HOME:-$HOME/.local/share}/dynamicalsystem/data
WATERMARK_FILE=watermarks.dev.json
EOF
chmod 600 .env

echo ".env written: $(grep -c '^[A-Z]' .env) vars"
