name: Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  NAMESPACE: dynamicalsystem
  PACKAGE_NAME: gazette
  DOCKER_IMAGE: dynamicalsystem/gazette

jobs:
  build-python:
    runs-on: ubuntu-latest
    env:
      # Halogen configuration for tests (updated dependency v4)
      DYNAMICALSYSTEM_ENVIRONMENT: pytest
      DYNAMICALSYSTEM_FOLDER: /home/runner/.local/share
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    
    - name: Create config directory and files
      run: |
        mkdir -p /home/runner/.local/share/dynamicalsystem/config
        # Create gazette.pytest.env
        cat > /home/runner/.local/share/dynamicalsystem/config/gazette.pytest.env << 'EOF'
        CONTENT_GITHUB_URL=https://raw.githubusercontent.com/DynamicalSystem/content/main/
        CONTENT_GITHUB_TOKEN=${{ secrets.CONTENT_GITHUB_TOKEN }}
        WATERMARKS_WATERMARK_FILE=watermarks.pytests.json
        EOF
        # Create dynamicalsystem.pytest.env
        cat > /home/runner/.local/share/dynamicalsystem/config/dynamicalsystem.pytest.env << 'EOF'
        LOG_SIGNAL_IDENTITY=${{ secrets.LOG_SIGNAL_IDENTITY }}
        LOG_LEVEL=DEBUG
        EOF
        # Create data directory
        mkdir -p /home/runner/.local/share/dynamicalsystem/data
        cat > /home/runner/.local/share/dynamicalsystem/data/watermarks.pytests.json << 'EOF'
        {
          "signal_to_abyss": {
            "publisher": "Signal",
            "chart": "test",
            "placing": 32,
            "target": "${{ secrets.LOG_SIGNAL_TARGET }}"
          },
          "bluesky": {
            "publisher": "Bluesky",
            "chart": "test",
            "placing": 32,
            "target": "test"
          }
        }
        EOF
    
    - name: Run tests
      run: |
        # Enable verbose logging
        export PYTHONUNBUFFERED=1
        # Show environment variables for debugging
        echo "Environment variables:"
        env | grep -E "(DYNAMICALSYSTEM|CONTENT|WATERMARKS|PUBLISHERS|GITHUB)" | sort
        # Run tests with verbose output
        uv run pytest --pyargs dynamicalsystem.pytests -v -s --tb=short
    
    - name: Build package
      run: |
        uv build --wheel --package dynamicalsystem.gazette
    
    - name: Check package with twine
      run: |
        uvx twine check dist/*
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 5

  publish-pypi:
    needs: build-python
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  build-docker:
    needs: build-python
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          NAMESPACE=${{ env.NAMESPACE }}
          SCRIPT=${{ env.PACKAGE_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

  # Optional: Build Docker image only when PyPI publish succeeds (for tagged releases)
  build-docker-release:
    needs: publish-pypi
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    
    - name: Build and push Docker image (release)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          NAMESPACE=${{ env.NAMESPACE }}
          SCRIPT=${{ env.PACKAGE_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64